#!/bin/bash
#SBATCH --job-name=vlas
#SBATCH --output=/home/lfeng/task_logs/%j.log
#SBATCH --partition=h100
#SBATCH --qos=vita
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=64
#SBATCH --gpus-per-node=1
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mem=200G

source ~/miniconda3/etc/profile.d/conda.sh
conda activate motus

cd /home/quanyi/code/Motus

# Run the standalone inference verification script
python inference/standalone/standalone_inference.py
